let etapas = [
    {
        titulo: 'SENADOR',
        numeros: 3,
        candidatos:[
            {
                numero: '123',
                nome: 'Miguel Diaz',
                partido: 'PJ',
                fotos:[
                    {url: 'miguel-diaz.png', legenda: 'Senador'}
                ]

            },
            {
                numero: '456',
                nome: "Samantha LaRusso",
                partido: "PL",
                fotos: [
                    {url: 'Samantha-LaRusso.jpg', legenda: 'Senadora'}
                ]
            },
        ]
    },
    {
        titulo: 'PRESIDENTE',
        numeros: 2,
        candidatos: [
            {
                numero: '10',
                nome: "Mestre Miyagi",
                partido: "PL",
                vice: "Daniel LaRusso",
                fotos:[
                    {url: 'mestre miyagi.jpg', legenda: 'Presidente'},
                    {url: 'LaRusso.jpg', legenda: 'Vice-Presidente'}
                ]

            },
            {
                numero: '95',
                nome: "John Kreese",
                partido: "PJ",
                vice: "Johnny Lawrwnce",
                fotos:[
                    {url: "john kreese.jpg", legenda:"Presidente"},
                    {url:"johnny-lawrence.png", legenda: "Vice-Presidente"}
                ]
            },
        ]
    }
]